### ISSUE TITLE
FYI: This Issue Tracker has been abandoned. EE7 BS all over again. None of the original people involved work for Oracle any more.

### ISSUE THREAD

**Issue by etay2000** [jersey/jersey#3710] opened 2017-10-31 16:59 UTC
In case anyone was wondering, none of the original people involved with the Jersey project work at Oracle anymore, and currently there is no one assigned to maintain it. Jersey was released and abandoned within a couple of months, smells like EE7 all over again. It might not be a good idea to bet the farm on EE8.

**Comment by m0mus** [comment] 2017-10-31 20:24
This is not true. Closing as not a bug.

**Closed by m0mus** 2017-10-31 20:24 UTC

**Comment by blling** [comment] 2017-10-31 21:49
The issues is no one answer quickly,  but this question is closed quickly. 
I am interesting if jersey is `abandoned` ?

**Comment by m0mus** [comment] 2017-10-31 22:39
Jersey is not abandoned. My team is responsible to maintain it.

**Comment by roytmana** [comment] 2018-03-05 13:52
@m0mus could you share what your team is doing/planning to do and what's jersey road map near future and beyond?
To an outside observer, it appears to be near zero activity around Jersey - not how it used to be when it was a vibrant exciting project (I used it from the very early versions). What about the work to make injection frameworks pluggable (pure CDI, HK2 etc) that was started a while ago? Is it abandoned?

**Comment by jansupol** [comment] 2018-03-05 18:36
@roytmana I agree that we should communicate the plans and activities around Jersey more. We are trying to find a proper communication channel for that. 

The short term plan is a donation of Jersey to Eclipse Foundation. For this to happen, we need to keep Jersey stable, without new dependencies and features that brings new complexities to the donation. Jersey is a large project that needs to be thoroughly validated for potential legal issues, and it takes time of many people. For this, it may occur to you as there is virtually no activity, but you can believe me, there is much headache.  The good news, we are getting there, hopefully within few weeks. Please follow the ee4j mailing lists.

Once in the Foundation, I assume the activity around Jersey will be tremendous, even greater than one can see around e.g. JAX-RS. However, we need to keep the new features in future branches for a while, since the first release of Jersey in the Foundation is to be compatible with Java EE 8. That's a requirement for all donated Java EE projects.

Regarding the plugable injections, it really is our wish to have it, though it seems not every injection framework is capable of handling complete feature set Jersey offers. Unfortunately, there are other tasks that also have high priorities, such as full JDK 9 support.

**Comment by roytmana** [comment] 2018-03-05 19:05
thank you @jansupol for the update. It is very helpful. Please do publish things like this for the community to see (I would say jersey.github.io news section/blog is perfectly fine place for it 
Jersey is a very popular framework please keep it going. 
As for pluggable injection framework, from my perspective just two would be enough - an internal one like you have now with no CDI support and CDI 2.x based but my take on this is admittedly is very narrow :-)
