### ISSUE TITLE
Jersey fails to create two instances of javax.ws.rs.Application in a single servlet context (WAR)

### ISSUE THREAD

**Issue by roytmana** [jersey/jersey#3624] opened 2017-07-20 22:47 UTC
Jersey 2.5.1 with CDI integration with Weld 3.0 enabled fails to create two instances of javax.ws.rs.Application

I am not sure what if JAX-RS specs say about creating multiple instances of the Application but it would be very helpful for  my use case (separate service management API from actual services api provided)

```
20-Jul-2017 18:37:43.444 SEVERE [ajp-nio-8809-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet jaxrs-api
 javax.ws.rs.WebApplicationException: Trying to register multiple service locators into single service locator application.
	at org.glassfish.jersey.ext.cdi1x.internal.SingleHk2LocatorManager.registerLocator(SingleHk2LocatorManager.java:65)
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.addLocator(CdiComponentProvider.java:790)
	at org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.initialize(CdiComponentProvider.java:198)
	at org.glassfish.jersey.server.ApplicationHandler$4.get(ApplicationHandler.java:408)
	at org.glassfish.jersey.server.ApplicationHandler$4.get(ApplicationHandler.java:399)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
	at org.glassfish.jersey.server.ApplicationHandler.createApplication(ApplicationHandler.java:366)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:342)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:779)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:133)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pavelbucek** [comment] 2017-07-21 08:20
Hi,
I don't see how would that be possible in single war.
What you might want to do is to create EAR and create separate war files for both of your APIs. In that case, everything should work, since the app context should be different.
Regards,
Pavel

**Comment by pavelbucek** [comment] 2017-07-21 08:20
closing, since this is not a bug / enhancement we can implement at this moment.

**Closed by pavelbucek** 2017-07-21 08:20 UTC
